# 构建镜像
FROM blazesnow/xcaddy:alpine AS builder

# 设置工作目录
WORKDIR /build

# 构建可执行文件
RUN xcaddy build --with $xcaddy_path

# 最终镜像
FROM alpine:latest

# 设置存储目录
ENV XDG_CONFIG_HOME /config
ENV XDG_DATA_HOME /data

# 补齐依赖
RUN apk add --no-cache ca-certificates libcap mailcap

# 复制可执行文件
COPY --from=builder /build/caddy /usr/bin/caddy

# 设置可执行文件权限
RUN chmod 700 /usr/bin/caddy

# 复制默认配置文件
COPY ./Caddyfile /etc/caddy/Caddyfile

# 开放端口
EXPOSE 80 443 443/udp 2019

# 运行命令
CMD ["/usr/bin/caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
