name: Version

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        # vX.Y.Z-beta.N 视为预发布（Prerelease）
        prerelease: ${{ contains(github.ref_name, '-beta') }}
